#!/usr/bin/env bash

if [ $# -eq 0 ]
then
    cd /home/$USER

else
    if [ "$1" == ".." ]
    then
        cd ..
    else
        if [ -d $(pwd)/$1 ]
        then
            cd $(pwd)/$1
        else
            read -r -p "the directory does not exist do you want to create one" response
            case "$response" in
                [yY])
                    echo "Creating directory $1"
                    mkdir $(pwd)/$1
                    cd $(pwd)/$1
                    ;;
                *)
                    echo "Operation cancelled."
                    exit 1
                    ;;
            esac
        fi
    fi
fi
